### ISSUE TITLE
layout results a little messy

### ISSUE THREAD

**Issue by Joppla** [csicar/Ning#32]
See screenshot of my Samsung S9 phone with android 10:

![Screenshot_20201008-191714_Ning](https://user-images.githubusercontent.com/25467829/95492310-2cbb8600-099b-11eb-8bd3-1da28ca28b75.jpg)

**Comment by csicar** [comment]
You probably got the version from F-Droid right? 

The problem should be fixed on the most up to date apk in the releases. https://github.com/csicar/Ning/releases/tag/v1.2.4

**Comment by Joppla** [comment]
Yes, I took it from fdroid.
Met vriendelijke groet,

Jop
(Vanaf mijn mobiel verzonden, dus waarschijnlijk te kort en te bondig)

9 okt. 2020 12:30:51 Carsten Csiky <notifications@github.com>:

**Comment by cdonner** [comment]
I just installed 1.2.4. The issue is still present.
![Screenshot_20201227-184827](https://user-images.githubusercontent.com/2066123/103181946-cd239700-4874-11eb-9c36-c605dc2520e4.png)

**Comment by csicar** [comment]
Thank you for providing the details. I'll see if I can fix that

**Comment by csicar** [comment]
Auto-resizing should be fixed in the pre-release https://github.com/csicar/Ning/releases/tag/v1.2.5-alpha-1

**Comment by csicar** [comment]
I'll assume this is fixed. If not please repoen the issue
